version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli
    working_directory: ~/opg-common-utils
    steps:
      - checkout
      - run: sudo composer self-update
      - run: composer install -n --prefer-dist
      - run: composer test-unit
      - run: composer test-phpstan
